<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.github.fanzezhen</groupId>
    <artifactId>fun-demo-java</artifactId>
    <version>${revision}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>fun-demo-mdm</artifactId>
  <name>${project.artifactId}</name>

  <properties>
  </properties>
  
  <dependencies>
    <dependency>
      <groupId>com.github.fanzezhen</groupId>
      <artifactId>fun-framework-core-all</artifactId>
    </dependency>
    <!-- MyBatis-Plus 增强（包含自动填充、逻辑删除、乐观锁等） -->
    <dependency>
      <groupId>com.github.fanzezhen</groupId>
      <artifactId>fun-framework-data-mp-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <!-- 接口文档 -->
    <dependency>
      <groupId>com.github.fanzezhen</groupId>
      <artifactId>fun-framework-spring-doc</artifactId>
    </dependency>
    <!-- 测试依赖 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
    </plugins>
  </build>

</project>
