# H2 \u6587\u4EF6\u6570\u636E\u5E93\u914D\u7F6E\uFF08\u5F00\u53D1\u73AF\u5883\uFF0C\u6570\u636E\u6301\u4E45\u5316\uFF09
spring.datasource.url=jdbc:h2:file:./data/demo;MODE=MySQL;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
# \u8FDE\u63A5\u6C60\u4E2D\u6700\u5927\u7684\u6D3B\u8DC3\u8FDE\u63A5\u6570
spring.datasource.tomcat.max-active=10

# \u542F\u7528 SQL \u521D\u59CB\u5316
spring.sql.init.mode=always
spring.sql.init.platform=h2
spring.sql.init.schema-locations=classpath:schema-h2.sql
spring.sql.init.data-locations=classpath:data-h2.sql
