spring.application.name=fun-demo-framework-spring-doc
fun.core.web.response-ignore-wrap-paths=/**
fun.log.level-map.[*.log.*]=INFO
fun.log.level-map.[com.*]=INFO
fun.log.file-path=${spring.application.name}/target/logs
logging.level.root=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n
logging.pattern.file=${logging.pattern.console}
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.github.fanzezhen
springdoc.paths-to-match=/**
