spring.application.name=fun-demo-framework-jasypt
logging.level.root=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n
logging.pattern.file=${logging.pattern.console}
jasypt.encryptor.bootstrap=true
jasypt.encryptor.bean=funSM2StringEncryptor
jasypt.encryptor.property.prefix=ENC(
jasypt.encryptor.property.suffix=)
fun.demo.jasypt.test-param=ENC(BFthJg4G9d0Ud7xFGKVB3vjVJ61yt3DKOXuRnws/FvzpSbUHqdpZ0JVF5xtEh7R8LUmDC35athF1fS80YlagFnWTBWXBzpnZ6RhbeDZW44hBx0SE8kygLPJhgY/DdMrXhvDU8gduSD5O`MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQg+MxXxSMFFgNtXGoFzkH3TJg0jXAo2J5XnM8isT7i0higCgYIKoEcz1UBgi2hRANCAARiDlNDvfGANqiqPHLWUN1mg1nz+4hN/06skj9DelWhIDK8IQ35NvFqf8dWoJkQ0KkxNvbuneWO0xt/e3fOgWkU`MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEYg5TQ73xgDaoqjxy1lDdZoNZ8/uITf9OrJI/Q3pVoSAyvCEN+Tbxan/HVqCZENCpMTb27p3ljtMbf3t3zoFpFA==)
